### ISSUE TITLE
Чекстайлы не пройдут, сделай paramCounter, когда идешь забирать параметры из ResultSet пиши paramCounter++

### ISSUE THREAD

**Issue by k1b24** [Emented/progLab_7#2]
https://github.com/Emented/progLab_7/blob/62fc5b966d361fa70217decbc7e5055ac22a2e0e/lab-server/src/main/java/emented/lab7/server/db/DBManager.java#L61-L96

**Comment by Emented** [comment]
нахуа?

**Comment by Emented** [comment]
у меня энивей падают чекстайлы на конструкторе commandmanagera

**Comment by k1b24** [comment]
убедил
